/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalobjetos.VistaControlador;

import finalobjetos.Modelo.Equipo;
import finalobjetos.Modelo.Proyecto;
import finalobjetos.Modelo.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author facuu
 */
public class AdministrarUsuariosForm extends javax.swing.JFrame {
    private Menu menu;
    private CrearUsuarioForm nuevoUsuario;
    private CrearEquipoForm nuevoEquipo;
    private EditarUsuarioForm editarUsuario;
    private ArrayList<Usuario> usuarios;
    private ArrayList<Equipo> equipos;

    /**
     * Creates new form AdministrarUsuariosForm
     * @param aThis
     */

    public AdministrarUsuariosForm(Menu aThis) {
        initComponents();
        this.menu = aThis;
        this.nuevoUsuario = new CrearUsuarioForm(this);
        this.nuevoUsuario.setLocationRelativeTo(null);
        this.nuevoEquipo = new CrearEquipoForm(this);
        this.nuevoEquipo.setLocationRelativeTo(null);
        this.editarUsuario = new EditarUsuarioForm(this);
        this.editarUsuario.setLocationRelativeTo(null);
        this.botonCrearEquipo.setVisible(false);
        this.etiquetaError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        botonCrearEquipo = new javax.swing.JButton();
        etiquetaError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuarios");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Contraseña", "Admin", "Equipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        botonCrearEquipo.setText("Crear equipo");
        botonCrearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearEquipoActionPerformed(evt);
            }
        });

        etiquetaError.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaError.setText("Debe seleccionar un usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonCrearEquipo)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaError)
                        .addGap(116, 116, 116))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botonCrearEquipo))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.tabla.getSelectedRow() != -1) {
            this.setVisible(false);
            this.editarUsuario.setElementos(this.equipos, this.usuarios.get(this.tabla.getSelectedRow()));
            this.editarUsuario.setVisible(true);
            this.etiquetaError.setVisible(false);
        }else{
            this.etiquetaError.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        this.nuevoUsuario.setUsuarios(this.usuarios);
        this.nuevoUsuario.setEquipos(this.equipos);
        this.nuevoUsuario.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botonCrearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearEquipoActionPerformed
        this.setVisible(false);
        this.nuevoEquipo.setEquipos(this.equipos);
        this.nuevoEquipo.setUsuarios(this.usuarios);
        this.nuevoEquipo.setVisible(true);
    }//GEN-LAST:event_botonCrearEquipoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this.tabla.getSelectedRow() != -1) {
            ArrayList <Proyecto> aux = this.usuarios.get(this.tabla.getSelectedRow()).getProyectos();
            for (int i = 0; i < aux.size(); i++) {
                aux.get(i).getMiembros().remove(this.usuarios.get(this.tabla.getSelectedRow()));
            }
            int equipo = this.equipos.indexOf(this.usuarios.get(this.tabla.getSelectedRow()).getEquipo());
            this.equipos.get(equipo).getMiembros().remove(this.usuarios.get(this.tabla.getSelectedRow()));
            this.usuarios.remove(this.tabla.getSelectedRow());
            this.llenarTabla();
        }else{
            this.etiquetaError.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearEquipo;
    private javax.swing.JLabel etiquetaError;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    void setEquipo(ArrayList<Equipo> equipos) {
        this.equipos = equipos;
    }

    void setUsuarios(ArrayList<Usuario> usuarios) {
        this.usuarios = usuarios;
        this.llenarTabla();
    }
    
    public void addRowToJTable(ArrayList <Usuario> lista){
        DefaultTableModel model = (DefaultTableModel) this.tabla.getModel();
        Object rowData[] = new Object[5];
        if (!lista.isEmpty()) {
            for (int i = 0; i < (lista.size()); i++) {
                rowData[0] = lista.get(i).getUsuarioID();
                rowData[1] = lista.get(i).getNombre();
                rowData[2] = lista.get(i).getContraseña();
                rowData[3] = lista.get(i).getAdmin();
                rowData[4] = lista.get(i).getEquipo();
                model.addRow(rowData);
            }
        }
        
    }
    
    public void clearJTable(){
        DefaultTableModel model = (DefaultTableModel) this.tabla.getModel();
        int filas = model.getRowCount();
        for (int i = 0; i < filas; i++) {
            model.removeRow(0);
        }
    }

    public void llenarTabla() {
        this.clearJTable();
        this.addRowToJTable(this.usuarios);
    }
}
