/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalobjetos.VistaControlador;

import finalobjetos.Modelo.Equipo;
import finalobjetos.Modelo.Estado;
import finalobjetos.Modelo.Item;
import finalobjetos.Modelo.TipoItem;
import finalobjetos.Modelo.Usuario;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author facuu
 */
public class AltaItemForm extends javax.swing.JFrame {
    private CrearProyectoForm proyectoNuevo;
    private CrearTipoItemForm nuevoTipo;
    private ArrayList <TipoItem> tiposItem;
    private ItemsForm verProyecto;
    private ArrayList <Item> items;
    private Usuario usuario;
    private ArrayList<Equipo> equipos;

    /**
     * Creates new form AltaItemForm
     * @param aThis
     */


    public AltaItemForm(CrearProyectoForm aThis) {
        initComponents();
        this.proyectoNuevo = aThis;
        this.verProyecto = null;
        this.nuevoTipo = new CrearTipoItemForm(this);
        this.nuevoTipo.setLocationRelativeTo(null);
        this.etiquetaError.setVisible(false);
    }
    
    public AltaItemForm(ItemsForm aThis) {
        initComponents();
        this.verProyecto = aThis;
        this.proyectoNuevo = null;
        this.nuevoTipo = new CrearTipoItemForm(this);
        this.nuevoTipo.setLocationRelativeTo(null);
        this.etiquetaError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboPrioridad = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboEquipo = new javax.swing.JComboBox();
        etiquetaError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel3.setText("Tipo:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "reporte de bug", "ampliacion", "mejora", "nuevo requerimiento" }));

        jLabel4.setText("Prioridad:");

        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Alta de un item");

        jLabel6.setText("Equipo:");

        etiquetaError.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaError.setText("Verifique el nombre del nuevo item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboPrioridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreText)
                                    .addComponent(comboEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaError)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(etiquetaError)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        if (this.verProyecto == null) {
            this.limpiarEquipos();
            this.proyectoNuevo.setVisible(true);
        }else{
            this.verProyecto.inicializarItems(items);
            this.limpiarEquipos();
            this.verProyecto.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.nombreText != null) {
            Item nuevo = new Item();
            nuevo.setNombre(this.nombreText.getText());
            nuevo.setPrioridad(this.getPrioridad());
            nuevo.setTipoItem(this.getTipoItem());
            nuevo.setEquipo(this.getEquipo());
            Estado historial = new Estado();
            historial.setResponsable(this.usuario.getNombre());
            nuevo.getHistorial().add(historial);
            Estado estado = new Estado();
            estado.setResponsable(this.usuario.getNombre());
            nuevo.setEstadoActual(estado);
            this.items.add(nuevo);
            this.setVisible(false);
            if (this.verProyecto == null) {
                this.proyectoNuevo.setVisible(true);
            }else{
                this.verProyecto.inicializarItems(items);
                this.verProyecto.setVisible(true);
            }
            this.etiquetaError.setVisible(false);
        }else{
            this.etiquetaError.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboEquipo;
    private javax.swing.JComboBox comboPrioridad;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JLabel etiquetaError;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreText;
    // End of variables declaration//GEN-END:variables

    void setItems(ArrayList <Item> items) {
        this.items = items;
    }

    private String getPrioridad() {
        switch (this.comboPrioridad.getSelectedIndex()){
            case 0: return "Alta";
                
            case 1: return "Media";
                
            case 2: return "Baja";
                
        }
        return null;
    }


    private String getTipoItem() {
        switch (this.comboTipo.getSelectedIndex()){
            case 0: return "reporte de bug";
            case 1: return "ampliacion";
            case 2: return "mejora";
            case 3: return "nuevo requerimiento";
        }
            
        return null;
    }

    void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    void setEquipos(ArrayList<Equipo> equipos) {
        this.equipos = equipos;
        for (int i = 0; i < this.equipos.size(); i++) {
            this.comboEquipo.addItem(this.equipos.get(i));
        }
    }

    private void limpiarEquipos() {
        this.comboEquipo.removeAllItems();
    }

    private Equipo getEquipo() {
        return this.equipos.get(this.comboEquipo.getSelectedIndex());
    }
}
