/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalobjetos.VistaControlador;

import finalobjetos.Modelo.Estado;
import finalobjetos.Modelo.Item;
import finalobjetos.Modelo.Mensaje;
import finalobjetos.Modelo.Proyecto;
import finalobjetos.Modelo.TipoItem;
import finalobjetos.Modelo.Usuario;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author facuu
 */
public class VerItemForm extends javax.swing.JFrame {
    private ItemsForm items;
    private HistorialResponsablesForm historial;
    private Item item;
    private Proyecto proyecto;
    private Usuario usuario;

    /**
     * Creates new form VerItemForm
     * @param aThis
     */
    public VerItemForm(ItemsForm aThis) {
        initComponents();
        this.items = aThis;
        this.historial = new HistorialResponsablesForm(this);
        this.historial.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonAvanzarEstado = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        etiquetaProximoEstado = new javax.swing.JLabel();
        estadosCombo = new javax.swing.JComboBox();
        etiquetaNuevoResponsable = new javax.swing.JLabel();
        comboResponsables = new javax.swing.JComboBox();
        botonAsignar = new javax.swing.JButton();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaEstado = new javax.swing.JLabel();
        etiquetaPrioridad = new javax.swing.JLabel();
        etiquetaEquipo = new javax.swing.JLabel();
        etiquetaTipo = new javax.swing.JLabel();
        etiquetaResponsable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel3.setText("Estado:");

        jLabel4.setText("Prioridad:");

        jLabel5.setText("Equipo asignado:");

        jLabel6.setText("Tipo:");

        jButton1.setText("Ver historial de responsables");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Responsable:");

        botonAvanzarEstado.setText("Avanzar estado");
        botonAvanzarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAvanzarEstadoActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        etiquetaProximoEstado.setText("Proximo estado:");

        etiquetaNuevoResponsable.setText("Asignar nuevo responsable:");

        botonAsignar.setText("Asignar");
        botonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etiquetaProximoEstado)
                            .addGap(18, 18, 18)
                            .addComponent(estadosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etiquetaNuevoResponsable)
                            .addGap(18, 18, 18)
                            .addComponent(comboResponsables, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(botonAvanzarEstado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(etiquetaEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaPrioridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(botonAsignar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiquetaNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etiquetaEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(etiquetaPrioridad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etiquetaEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(etiquetaTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(etiquetaResponsable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaProximoEstado)
                    .addComponent(estadosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAvanzarEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNuevoResponsable)
                    .addComponent(comboResponsables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(botonAsignar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.historial.setHistorial(this.item.getHistorial());
        this.historial.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        this.items.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonAvanzarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAvanzarEstadoActionPerformed
        Object proximo = this.estadosCombo.getItemAt(this.estadosCombo.getSelectedIndex());
        this.item.getEstadoActual().setNombre(proximo.toString());
        Estado historial = new Estado();
        historial.setNombre(proximo.toString());
        historial.setResponsable(this.item.getEstadoActual().getResponsable());
        historial.setFecha(new Date());
        this.item.getHistorial().add(historial);
        this.etiquetaEstado.setText(proximo.toString());
        this.llenarComboEstados();
        Mensaje mensaje = new Mensaje();
        mensaje.setAsunto("Modificacion del estado de un item");
        mensaje.setContenido("Se modifico el estado del item '" + this.item.getNombre() + "' del proyecto '" + this.proyecto.getNombre() + "' al estado de: " + proximo.toString());
        for (int i = 0; i < this.proyecto.getMiembros().size(); i++) {
            this.proyecto.getMiembros().get(i).getMensajes().add(mensaje);
        }
        this.proyecto.getMiembros();
    }//GEN-LAST:event_botonAvanzarEstadoActionPerformed

    private void botonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarActionPerformed
        Object nuevo = this.comboResponsables.getItemAt(this.comboResponsables.getSelectedIndex());
        this.item.getEstadoActual().setResponsable(nuevo.toString());
        Estado historial = new Estado();
        historial.setNombre(this.item.getEstadoActual().getNombre());
        historial.setResponsable(nuevo.toString());
        historial.setFecha(new Date());
        this.item.getHistorial().add(historial);
        this.etiquetaResponsable.setText(nuevo.toString());
    }//GEN-LAST:event_botonAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignar;
    private javax.swing.JButton botonAvanzarEstado;
    private javax.swing.JComboBox comboResponsables;
    private javax.swing.JComboBox estadosCombo;
    private javax.swing.JLabel etiquetaEquipo;
    private javax.swing.JLabel etiquetaEstado;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNuevoResponsable;
    private javax.swing.JLabel etiquetaPrioridad;
    private javax.swing.JLabel etiquetaProximoEstado;
    private javax.swing.JLabel etiquetaResponsable;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    void setItem(Item itemVisto) {
        this.item = itemVisto;
        this.etiquetaNombre.setText(this.item.getNombre());
        this.etiquetaEstado.setText(this.item.getEstadoActual().getNombre());
        this.etiquetaPrioridad.setText(this.item.getPrioridad());
        this.etiquetaResponsable.setText(this.item.getEstadoActual().getResponsable());
        this.etiquetaEquipo.setText(this.item.getEquipo().getNombre());
        this.etiquetaTipo.setText(this.item.getTipoItem().getNombre());
        this.llenarComboEstados();
        this.llenarComboResponsables();
        
    }

    private void llenarComboEstados() {
        this.estadosCombo.removeAllItems();
        ArrayList <String> lista = this.item.getTipoItem().getWorkflow().getProximosEstados(this.item.getTipoItem().getNombre(), this.item.getEstadoActual());
        for (int i = 0; i < (lista.size()); i++) {
                this.estadosCombo.addItem(lista.get(i));
        }
    }

    void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    private void llenarComboResponsables() {
        this.comboResponsables.removeAllItems();
        ArrayList <Usuario> lista = this.proyecto.getMiembros();
        for (int i = 0; i < lista.size(); i++) {
            this.comboResponsables.addItem(lista.get(i).getNombre());
        }
    }

    private void verificarResponsable() {
        if ((this.item.getEstadoActual().getResponsable() == this.usuario.getNombre()) || this.usuario.getAdmin()) {
            this.etiquetaNuevoResponsable.setVisible(true);
            this.etiquetaProximoEstado.setVisible(true);
            this.comboResponsables.setVisible(true);
            this.estadosCombo.setVisible(true);
            this.botonAsignar.setVisible(true);
            this.botonAvanzarEstado.setVisible(true);
        }else{
            this.etiquetaNuevoResponsable.setVisible(false);
            this.etiquetaProximoEstado.setVisible(false);
            this.comboResponsables.setVisible(false);
            this.estadosCombo.setVisible(false);
            this.botonAsignar.setVisible(false);
            this.botonAvanzarEstado.setVisible(false);
        }
    }

    void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        this.verificarResponsable();
    }
}
